return {
  n = {
    ["<leader>ll"] = { function() vim.lsp.codelens.run() end, desc = "LSP CodeLens run" },
    ["<leader>lL"] = { function() vim.lsp.codelens.refresh() end, desc = "LSP CodeLens refresh" },

    ["<leader>r"] = { desc = "Rust" },
    ["<leader>rr"] = { function() vim.cmd.RustLsp "runnables" end, desc = "runnables" },
    ["<leader>re"] = { function() vim.cmd.RustLsp "expandMacro" end, desc = "expandMacro" },
    ["<leader>ru"] = { function() vim.cmd.RustLsp("moveItem", "up") end, desc = "moveItem" },
    ["<leader>rd"] = { function() vim.cmd.RustLsp("moveItem", "down") end, desc = "moveItem" },
    ["<leader>rha"] = { function() vim.cmd.RustLsp("hover", "actions") end, desc = "hover actions" },
    ["<leader>rhr"] = { function() vim.cmd.RustLsp("hover", "range") end, desc = "hover range" },
    ["<leader>rx"] = { function() vim.cmd.RustLsp "explainError" end, desc = "explainError" },
    ["<leader>rD"] = { function() vim.cmd.RustLsp "renderDiagnostic" end, desc = "renderDiagnostic" },
    ["<leader>ro"] = { function() vim.cmd.RustLsp "openCargo" end, desc = "openCargo" },
    ["<leader>rp"] = { function() vim.cmd.RustLsp "parentModule" end, desc = "parentModule" },
    ["<leader>rj"] = { function() vim.cmd.RustLsp "joinLines" end, desc = "joinLines" },
    ["<leader>rs"] = { function() vim.cmd.RustLsp("ssr", "query") end, desc = "ssr" },
    ["<leader>rc"] = { function() vim.cmd.RustLsp("crateGraph", "backend") end, desc = "crateGraph" },
    ["<leader>rt"] = { function() vim.cmd.RustLsp "syntaxTree" end, desc = "syntaxTree" },
    ["<leader>rvm"] = { function() vim.cmd.RustLsp("view", "mir") end, desc = "view mir" },
    ["<leader>rvh"] = { function() vim.cmd.RustLsp("view", "hir") end, desc = "view hir" },
    ["<leader>rf"] = { function() vim.cmd.RustLsp "flyCheck" end, desc = "flyCheck" },
    ["<leader>rl"] = { function() vim.cmd.RustLsp "logFile" end, desc = "logFile" },
  },
}
